---
apiVersion: v1
kind: Service
metadata:
  name: csi-azuredisk-controller
  namespace: kube-system
spec:
  selector:
    app: csi-azuredisk-controller
  ports:
    - port: 29604
      targetPort: 29604
  type: LoadBalancer
