apiVersion: v1
entries:
  azuredisk-csi-driver:
  - apiVersion: v1
    appVersion: v0.8.0
    created: "2020-08-09T12:26:05.802994718Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 1762b832389b4f7a5eab9748127fa6dbb85131485d67bc3fe485bbe86c468128
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v0.8.0/azuredisk-csi-driver-v0.8.0.tgz
    version: v0.8.0
  - apiVersion: v1
    appVersion: v0.7.0
    created: "2020-08-09T12:26:05.801868707Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: 29e21f686814f46c1edaaaa95ce2d25579ff1aad270c58b774bdb5a89858b8bf
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v0.7.0/azuredisk-csi-driver-v0.7.0.tgz
    version: v0.7.0
  - apiVersion: v1
    appVersion: v0.6.0
    created: "2020-08-09T12:26:05.800674195Z"
    description: Azure disk Container Storage Interface (CSI) Storage Plugin
    digest: b11d8dfee371ca7c63a1448ba27c1fd1f032ea33575fefeeb16927fc95d1eeb7
    name: azuredisk-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts/v0.6.0/azuredisk-csi-driver-v0.6.0.tgz
    version: v0.6.0
generated: "2020-08-09T12:26:05.799447083Z"
